export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <div>HI I AM THE LAYOUT CALL FOR ALL PAGES EVEN MDX</div>
        <div>{children}</div>
        </body>
    </html>
  )
}
